### ISSUE TITLE
有空来测试和参与开发我的项目吗

### ISSUE THREAD

**Issue by Pandaft** [maxmiku/ESurfingClientAutoConnect#1]
在你的主页没有找到联系方式，只能来这个项目提 issue 了。
我的学校校园网也是广东天翼校园网，具体项目可以进我的主页看。

**Comment by maxmiku** [comment]
最近学业有些繁忙，可能抽不出来空开发这个项目了😂

**Comment by maxmiku** [comment]
> 在你的主页没有找到联系方式，只能来这个项目提 issue 了。
> 
> 我的学校校园网也是广东天翼校园网，具体项目可以进我的主页看。

最近学业有些繁忙，可能抽不出来空开发这个项目了😂

**Comment by Pandaft** [comment]
😂学业重要，前辈加油！
